

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData  V2                                     /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

    
  $data.Entity.extend('PPAModel.MD_CALCUALTION', {
     'CALC_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'NAME': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':128 },
     'TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'DESCRIPTION': { 'type':'Edm.String','maxLength':512 },
     'PROGRAM': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY }
  });

  $data.Entity.extend('PPAModel.MD_DOM_VALUE', {
     'DOM_VAL_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'DOM_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'VALUE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':700 },
     'DESCRIPTION': { 'type':'Edm.String','maxLength':512 },
     'DOM_VAL_POS': { 'type':'Edm.Int16' },
     'MD_DOMAIN': { 'type':'PPAModel.MD_DOMAIN','required':true,'inverseProperty':'MD_DOM_VALUE' }
  });

  $data.Entity.extend('PPAModel.MD_DOMAIN', {
     'DOM_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'DOM_NAME': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':128 },
     'VALUE_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'RANGE_TYPE': { 'type':'Edm.String','maxLength':2 },
     'UOM_ID': { 'type':'Edm.String','maxLength':64 },
     'MD_DOM_VALUE': { 'type':'Array','elementType':'PPAModel.MD_DOM_VALUE','inverseProperty':'MD_DOMAIN' }
  });

  $data.Entity.extend('PPAModel.MD_DT_CAUSE', {
     'DT_CAU_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'NAME': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':128 },
     'DT_CLS_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'DESCRIPTION': { 'type':'Edm.String','maxLength':512 },
     'MD_DT_CLASSE': { 'type':'PPAModel.MD_DT_CLASSE','required':true,'inverseProperty':'MD_DT_CAUSE' }
  });

  $data.Entity.extend('PPAModel.MD_DT_CLASSE', {
     'DT_CLS_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'NAME': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':128 },
     'DESCRIPTION': { 'type':'Edm.String','maxLength':512 },
     'MD_DT_CAUSE': { 'type':'Array','elementType':'PPAModel.MD_DT_CAUSE','inverseProperty':'MD_DT_CLASSE' }
  });

  $data.Entity.extend('PPAModel.MD_EQPDT_PAR_TAG', {
     'PV_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
     'EVT_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_POS': { 'type':'Edm.Int16' },
     'PAR_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'REC_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'PAR_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'PM_EQP_DT_EVENT': { 'type':'PPAModel.PM_EQP_DT_EVENT','required':true,'inverseProperty':'MD_EQPDT_PAR_TAG' }
  });

  $data.Entity.extend('PPAModel.MD_EQPMAT_PAR_TAG', {
     'PV_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
     'OBJ_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_POS': { 'type':'Edm.Int16' },
     'PAR_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'REC_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'PAR_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'PM_EQP_CONSUMPTION': { 'type':'PPAModel.PM_EQP_CONSUMPTION','required':true,'inverseProperty':'MD_EQPMAT_PAR_TAG' }
  });

  $data.Entity.extend('PPAModel.MD_PAR_CATEGORY', {
     'PAR_CAT_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PAR_CAT_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_CAT_NAME': { 'type':'Edm.String','maxLength':128 }
  });

  $data.Entity.extend('PPAModel.MD_PAR_CLASSIFICATION', {
     'PAR_CLF_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_CAT_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PAR_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PAR_POS': { 'type':'Edm.Int16' }
  });

  $data.Entity.extend('PPAModel.MD_PARAMETER', {
     'PAR_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'DATA_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'PAR_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_NAME': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':128 },
     'PAR_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'DISPLAY_LEN': { 'type':'Edm.Int16' },
     'DISPLAY_NAME': { 'type':'Edm.String','maxLength':128 },
     'DOM_ID': { 'type':'Edm.String','maxLength':64 },
     'UOM_ID': { 'type':'Edm.String','maxLength':64 }
  });

  $data.Entity.extend('PPAModel.MD_UNITS_OF_MEASURE', {
     'UOM_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'OBJ_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'UOM_TEXT': { 'type':'Edm.String','maxLength':512 }
  });

  $data.Entity.extend('PPAModel.PM_CYC_TEAM', {
     'OBJ_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'SHF_CYC_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'SHF_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'CYC_POS': { 'type':'Edm.Int16','nullable':false,'required':true },
     'TEAM_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 }
  });

  $data.Entity.extend('PPAModel.PM_ENG_CONSUMPTION', {
     'OBJ_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'REC_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'ENG_ID_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':700 },
     'ENG_QTY_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':700 }
  });

  $data.Entity.extend('PPAModel.PM_EQP_CONSUMPTION', {
     'OBJ_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'EQP_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'SRC_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'CONDITION': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':700 },
     'BATCH_ID_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'CSM_MATID_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'CSM_MATQTY_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'UOM_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'MD_EQPMAT_PAR_TAG': { 'type':'Array','elementType':'PPAModel.MD_EQPMAT_PAR_TAG','inverseProperty':'PM_EQP_CONSUMPTION' },
     'PM_EQUIPMENT': { 'type':'PPAModel.PM_EQUIPMENT','required':true,'inverseProperty':'PM_EQP_CONSUMPTION' }
  });

  $data.Entity.extend('PPAModel.PM_EQP_DT_EVENT', {
     'EVT_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'EQP_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'EVT_NAME': { 'type':'Edm.String','maxLength':128 },
     'EVT_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'SRC_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'CONDITION': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':700 },
     'DT_CAU_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'MD_EQPDT_PAR_TAG': { 'type':'Array','elementType':'PPAModel.MD_EQPDT_PAR_TAG','inverseProperty':'PM_EQP_DT_EVENT' },
     'PM_EQUIPMENT': { 'type':'PPAModel.PM_EQUIPMENT','required':true,'inverseProperty':'PM_EQP_DT_EVENT' }
  });

  $data.Entity.extend('PPAModel.PM_EQP_LEVEL', {
     'LVL_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'NAME': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':128 },
     'PARENT': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'DESCRIPTION': { 'type':'Edm.String','maxLength':512 },
     'PM_EQUIPMENT': { 'type':'Array','elementType':'PPAModel.PM_EQUIPMENT','inverseProperty':'PM_EQP_LEVEL' }
  });

  $data.Entity.extend('PPAModel.PM_EQP_PERFORMANCE', {
     'OBJ_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'EQP_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PER_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'SPAN_UNIT': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'SPAN': { 'type':'Edm.Int16','nullable':false,'required':true },
     'TARGET': { 'type':'Edm.String','maxLength':700 },
     'ACT_TAG': { 'type':'Edm.String','maxLength':700 },
     'PM_EQUIPMENT': { 'type':'PPAModel.PM_EQUIPMENT','required':true,'inverseProperty':'PM_EQP_PERFORMANCE' }
  });

  $data.Entity.extend('PPAModel.PM_EQP_PROPERTY', {
     'EQP_PRP_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'EQP_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PAR_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PAR_POS': { 'type':'Edm.Int16' },
     'PAR_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'VALUE_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'HIGH_VALUE': { 'type':'Edm.String','maxLength':700 },
     'LOW_VALUE': { 'type':'Edm.String','maxLength':700 },
     'RANGE_TYPE': { 'type':'Edm.String','maxLength':2 },
     'PM_EQUIPMENT': { 'type':'PPAModel.PM_EQUIPMENT','required':true,'inverseProperty':'PM_EQP_PROPERTY' }
  });

  $data.Entity.extend('PPAModel.PM_EQP_QUALITY', {
     'OBJ_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'EQP_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'TOTAL_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'QUALIFY_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'REWORK_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'SCRAP_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'BATCH_ID_TAG': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
     'PM_EQUIPMENT': { 'type':'PPAModel.PM_EQUIPMENT','required':true,'inverseProperty':'PM_EQP_QUALITY' }
  });

  $data.Entity.extend('PPAModel.PM_EQUIPMENT', {
     'EQP_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'NAME': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':128 },
     'STATUS': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'PARENT': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'LVL_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'RT_TAG': { 'type':'Edm.String','maxLength':255 },
     'PER_CALC_ID': { 'type':'Edm.String','maxLength':64 },
     'DESCRIPTION': { 'type':'Edm.String','maxLength':512 },
     'QA_CALC_ID': { 'type':'Edm.String','maxLength':64 },
     'AVA_CALC_ID': { 'type':'Edm.String','maxLength':64 },
     'PM_EQP_CONSUMPTION': { 'type':'Array','elementType':'PPAModel.PM_EQP_CONSUMPTION','inverseProperty':'PM_EQUIPMENT' },
     'PM_EQP_DT_EVENT': { 'type':'Array','elementType':'PPAModel.PM_EQP_DT_EVENT','inverseProperty':'PM_EQUIPMENT' },
     'PM_EQP_LEVEL': { 'type':'PPAModel.PM_EQP_LEVEL','required':true,'inverseProperty':'PM_EQUIPMENT' },
     'PM_EQP_PERFORMANCE': { 'type':'Array','elementType':'PPAModel.PM_EQP_PERFORMANCE','inverseProperty':'PM_EQUIPMENT' },
     'PM_EQP_PROPERTY': { 'type':'Array','elementType':'PPAModel.PM_EQP_PROPERTY','inverseProperty':'PM_EQUIPMENT' },
     'PM_EQP_QUALITY': { 'type':'Array','elementType':'PPAModel.PM_EQP_QUALITY','inverseProperty':'PM_EQUIPMENT' }
  });

  $data.Entity.extend('PPAModel.PM_PER_DETAIL', {
     'PDTL_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PER_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'START_TIME': { 'type':'Edm.Int16','nullable':false,'required':true },
     'END_TIME': { 'type':'Edm.Int16','nullable':false,'required':true },
     'PRD_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'PM_PERIOD': { 'type':'PPAModel.PM_PERIOD','required':true,'inverseProperty':'PM_PER_DETAIL' }
  });

  $data.Entity.extend('PPAModel.PM_PERIOD', {
     'PER_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PER_NAME': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':128 },
     'SHF_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'START_TIME': { 'type':'Edm.Int16','nullable':false,'required':true },
     'END_TIME': { 'type':'Edm.Int16','nullable':false,'required':true },
     'PM_PER_DETAIL': { 'type':'Array','elementType':'PPAModel.PM_PER_DETAIL','inverseProperty':'PM_PERIOD' },
     'PM_SHIFT': { 'type':'PPAModel.PM_SHIFT','required':true,'inverseProperty':'PM_PERIOD' }
  });

  $data.Entity.extend('PPAModel.PM_SH_CYCLE', {
     'SHF_CYC_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'STATUS': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'SHF_CYC_LEN': { 'type':'Edm.Int16','nullable':false,'required':true },
     'START_D': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'START_POS': { 'type':'Edm.Int16','nullable':false,'required':true }
  });

  $data.Entity.extend('PPAModel.PM_SHIFT', {
     'SHF_ID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'SHF_NAME': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':128 },
     'START_TIME': { 'type':'Edm.Int16','nullable':false,'required':true },
     'END_TIME': { 'type':'Edm.Int16','nullable':false,'required':true },
     'PM_PERIOD': { 'type':'Array','elementType':'PPAModel.PM_PERIOD','inverseProperty':'PM_SHIFT' }
  });

  $data.Entity.extend('PPAModel.PPA_DT_RECORD', {
     'REC_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'EQP_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'D_RECORD': { 'type':'Edm.DateTime' },
     'DT_START_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'DT_END_TIME': { 'type':'Edm.DateTime' },
     'DT_CAU_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PROCESSED': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'D_UPDATE': { 'type':'Edm.DateTime' },
     'D_CALCULATE': { 'type':'Edm.DateTime' },
     'OPERATOR': { 'type':'Edm.String','maxLength':128 },
     'PPA_DTR_PARAMETER': { 'type':'Array','elementType':'PPAModel.PPA_DTR_PARAMETER','inverseProperty':'PPA_DT_RECORD' }
  });

  $data.Entity.extend('PPAModel.PPA_DTR_PARAMETER', {
     'PV_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
     'REC_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_POS': { 'type':'Edm.Int16' },
     'PAR_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'VALUE_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'HIGH_VALUE': { 'type':'Edm.String','maxLength':700 },
     'LOW_VALUE': { 'type':'Edm.String','maxLength':700 },
     'RANGE_TYPE': { 'type':'Edm.String','maxLength':2 },
     'PPA_DT_RECORD': { 'type':'PPAModel.PPA_DT_RECORD','required':true,'inverseProperty':'PPA_DTR_PARAMETER' }
  });

  $data.Entity.extend('PPAModel.PPA_ENG_CONSUMPTION', {
     'ENGC_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'D_PRODUCTION': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'ENGC_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'SHF_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PER_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'ENG_ID': { 'type':'Edm.String','maxLength':64 },
     'QUANTITY': { 'type':'Edm.Decimal' }
  });

  $data.Entity.extend('PPAModel.PPA_ENGC_RECORD', {
     'REC_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'D_RECORD': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'ENGC_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'SHF_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PER_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'BATCH_ID': { 'type':'Edm.String','maxLength':64 },
     'ENG_ID': { 'type':'Edm.String','maxLength':64 },
     'QUANTITY': { 'type':'Edm.Decimal' },
     'PROCESSED': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'D_UPDATE': { 'type':'Edm.DateTime' },
     'OPERATOR': { 'type':'Edm.String','maxLength':128 }
  });

  $data.Entity.extend('PPAModel.PPA_MAT_CONSUMPTION', {
     'MATC_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'CSM_MAT_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'MAT_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'QUANTITY': { 'type':'Edm.Decimal' },
     'UOM_ID': { 'type':'Edm.String','maxLength':64 },
     'REMARK': { 'type':'Edm.String','maxLength':512 },
     'PPA_MATERIAL': { 'type':'PPAModel.PPA_MATERIAL','required':true,'inverseProperty':'PPA_MAT_CONSUMPTION' }
  });

  $data.Entity.extend('PPAModel.PPA_MAT_PARAMETER', {
     'PV_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
     'MAT_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_POS': { 'type':'Edm.Int16' },
     'PAR_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'VALUE_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'HIGH_VALUE': { 'type':'Edm.String','maxLength':700 },
     'LOW_VALUE': { 'type':'Edm.String','maxLength':700 },
     'RANGE_TYPE': { 'type':'Edm.String','maxLength':2 },
     'PPA_MATERIAL': { 'type':'PPAModel.PPA_MATERIAL','required':true,'inverseProperty':'PPA_MAT_PARAMETER' }
  });

  $data.Entity.extend('PPAModel.PPA_MAT_STRUCTURE_ELEMENT', {
     'MAT_STRE_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'MAT_STRE_POS': { 'type':'Edm.Int16','nullable':false,'required':true },
     'MAT_STRE_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'PRED_MAT_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'SUCC_MAT_NO': { 'type':'Edm.Decimal','nullable':false,'required':true }
  });

  $data.Entity.extend('PPAModel.PPA_MATC_RECORD', {
     'REC_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'D_RECORD': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'MATC_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'SHF_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PER_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'BATCH_ID': { 'type':'Edm.String','maxLength':64 },
     'CON_MAT_ID': { 'type':'Edm.String','maxLength':64 },
     'QUANTITY': { 'type':'Edm.Decimal' },
     'PROCESSED': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'D_UPDATE': { 'type':'Edm.DateTime' },
     'OPERATOR': { 'type':'Edm.String','maxLength':128 },
     'PPA_MATCR_PARAMETER': { 'type':'Array','elementType':'PPAModel.PPA_MATCR_PARAMETER','inverseProperty':'PPA_MATC_RECORD' }
  });

  $data.Entity.extend('PPAModel.PPA_MATCR_PARAMETER', {
     'PV_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
     'REC_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PAR_POS': { 'type':'Edm.Int16' },
     'PAR_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'VALUE_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'HIGH_VALUE': { 'type':'Edm.String','maxLength':700 },
     'LOW_VALUE': { 'type':'Edm.String','maxLength':700 },
     'RANGE_TYPE': { 'type':'Edm.String','maxLength':2 },
     'PPA_MATC_RECORD': { 'type':'PPAModel.PPA_MATC_RECORD','required':true,'inverseProperty':'PPA_MATCR_PARAMETER' }
  });

  $data.Entity.extend('PPAModel.PPA_MATERIAL', {
     'MAT_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'EXT_MAT_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'STATUS': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'D_PRODUCTION': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'MAT_CLS_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'MAT_QTY': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'UOM_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PO_ID': { 'type':'Edm.String','maxLength':64 },
     'PPA_MAT_CONSUMPTION': { 'type':'Array','elementType':'PPAModel.PPA_MAT_CONSUMPTION','inverseProperty':'PPA_MATERIAL' },
     'PPA_MAT_PARAMETER': { 'type':'Array','elementType':'PPAModel.PPA_MAT_PARAMETER','inverseProperty':'PPA_MATERIAL' }
  });

  $data.Entity.extend('PPAModel.PPA_OEE_SUMMARY', {
     'SUM_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'EQP_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'SHF_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PER_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PER_START_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'PER_END_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'PL_PRD_TIME': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'ACT_PRD_TIME': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'SCH_DT_TIME': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'UNSCH_DT_TIME': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'UNSCH_DT_CNT': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'TOTAL_ITEMS': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'QA_ITEMS': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'REWORK_ITEMS': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'SCRAP_ITEMS': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'OEE_AVA': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'OEE_PER': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'OEE_QUA': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'D_UPDATE': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'OEE_COM': { 'type':'Edm.Decimal','nullable':false,'required':true }
  });

  $data.Entity.extend('PPAModel.PPA_PER_DETAIL', {
     'PDTL_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'PER_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'START_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'END_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'PRD_TYPE': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'PPA_PERIOD': { 'type':'PPAModel.PPA_PERIOD','required':true,'inverseProperty':'PPA_PER_DETAIL' }
  });

  $data.Entity.extend('PPAModel.PPA_PER_RECORD', {
     'REC_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'EQP_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'D_RECORD': { 'type':'Edm.DateTime' },
     'REC_START_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'REC_END_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'SHF_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PER_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'BATCH_ID': { 'type':'Edm.String','maxLength':64 },
     'IDEAL': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'ACTUAL': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PROCESSED': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'D_UPDATE': { 'type':'Edm.DateTime' },
     'OPERATOR': { 'type':'Edm.String','maxLength':128 }
  });

  $data.Entity.extend('PPAModel.PPA_PERIOD', {
     'PER_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'PER_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'SHF_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'START_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'END_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'PPA_PER_DETAIL': { 'type':'Array','elementType':'PPAModel.PPA_PER_DETAIL','inverseProperty':'PPA_PERIOD' },
     'PPA_SHIFT': { 'type':'PPAModel.PPA_SHIFT','required':true,'inverseProperty':'PPA_PERIOD' }
  });

  $data.Entity.extend('PPAModel.PPA_QA_RECORD', {
     'REC_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'EQP_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'D_RECORD': { 'type':'Edm.DateTime' },
     'REC_START_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'REC_END_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'SHF_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PER_NO': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'BATCH_ID': { 'type':'Edm.String','maxLength':64 },
     'TOTAL': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'REWORK': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'SCRAP': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'PROCESSED': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
     'D_UPDATE': { 'type':'Edm.DateTime' },
     'OPERATOR': { 'type':'Edm.String','maxLength':128 },
     'QUALIFY': { 'type':'Edm.Decimal','nullable':false,'required':true }
  });

  $data.Entity.extend('PPAModel.PPA_SHIFT', {
     'SHF_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'SHF_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'START_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'END_TIME': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'TEAM_ID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':64 },
     'PPA_PERIOD': { 'type':'Array','elementType':'PPAModel.PPA_PERIOD','inverseProperty':'PPA_SHIFT' }
  });

  $data.Entity.extend('PPAModel.SYS_USER_SESSION', {
     'SESSION_NO': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'TERMINAL_ID': { 'type':'Edm.String','maxLength':64 },
     'USER_ID': { 'type':'Edm.String','maxLength':64 },
     'ROLE_ID': { 'type':'Edm.String','maxLength':64 },
     'SESSION_START_DATE': { 'type':'Edm.DateTime','nullable':false,'required':true },
     'SESSION_END_DATE': { 'type':'Edm.DateTime' }
  });

  $data.EntityContext.extend('AicTech.PPA.DataModel.PPAEntities', {
     'MD_CALCUALTION': { type: $data.EntitySet, elementType: PPAModel.MD_CALCUALTION},
     'MD_DOM_VALUE': { type: $data.EntitySet, elementType: PPAModel.MD_DOM_VALUE},
     'MD_DOMAIN': { type: $data.EntitySet, elementType: PPAModel.MD_DOMAIN},
     'MD_DT_CAUSE': { type: $data.EntitySet, elementType: PPAModel.MD_DT_CAUSE},
     'MD_DT_CLASSE': { type: $data.EntitySet, elementType: PPAModel.MD_DT_CLASSE},
     'MD_EQPDT_PAR_TAG': { type: $data.EntitySet, elementType: PPAModel.MD_EQPDT_PAR_TAG},
     'MD_EQPMAT_PAR_TAG': { type: $data.EntitySet, elementType: PPAModel.MD_EQPMAT_PAR_TAG},
     'MD_PAR_CATEGORY': { type: $data.EntitySet, elementType: PPAModel.MD_PAR_CATEGORY},
     'MD_PAR_CLASSIFICATION': { type: $data.EntitySet, elementType: PPAModel.MD_PAR_CLASSIFICATION},
     'MD_PARAMETER': { type: $data.EntitySet, elementType: PPAModel.MD_PARAMETER},
     'MD_UNITS_OF_MEASURE': { type: $data.EntitySet, elementType: PPAModel.MD_UNITS_OF_MEASURE},
     'PM_CYC_TEAM': { type: $data.EntitySet, elementType: PPAModel.PM_CYC_TEAM},
     'PM_ENG_CONSUMPTION': { type: $data.EntitySet, elementType: PPAModel.PM_ENG_CONSUMPTION},
     'PM_EQP_CONSUMPTION': { type: $data.EntitySet, elementType: PPAModel.PM_EQP_CONSUMPTION},
     'PM_EQP_DT_EVENT': { type: $data.EntitySet, elementType: PPAModel.PM_EQP_DT_EVENT},
     'PM_EQP_LEVEL': { type: $data.EntitySet, elementType: PPAModel.PM_EQP_LEVEL},
     'PM_EQP_PERFORMANCE': { type: $data.EntitySet, elementType: PPAModel.PM_EQP_PERFORMANCE},
     'PM_EQP_PROPERTY': { type: $data.EntitySet, elementType: PPAModel.PM_EQP_PROPERTY},
     'PM_EQP_QUALITY': { type: $data.EntitySet, elementType: PPAModel.PM_EQP_QUALITY},
     'PM_EQUIPMENT': { type: $data.EntitySet, elementType: PPAModel.PM_EQUIPMENT},
     'PM_PER_DETAIL': { type: $data.EntitySet, elementType: PPAModel.PM_PER_DETAIL},
     'PM_PERIOD': { type: $data.EntitySet, elementType: PPAModel.PM_PERIOD},
     'PM_SH_CYCLE': { type: $data.EntitySet, elementType: PPAModel.PM_SH_CYCLE},
     'PM_SHIFT': { type: $data.EntitySet, elementType: PPAModel.PM_SHIFT},
     'PPA_DT_RECORD': { type: $data.EntitySet, elementType: PPAModel.PPA_DT_RECORD},
     'PPA_DTR_PARAMETER': { type: $data.EntitySet, elementType: PPAModel.PPA_DTR_PARAMETER},
     'PPA_ENG_CONSUMPTION': { type: $data.EntitySet, elementType: PPAModel.PPA_ENG_CONSUMPTION},
     'PPA_ENGC_RECORD': { type: $data.EntitySet, elementType: PPAModel.PPA_ENGC_RECORD},
     'PPA_MAT_CONSUMPTION': { type: $data.EntitySet, elementType: PPAModel.PPA_MAT_CONSUMPTION},
     'PPA_MAT_PARAMETER': { type: $data.EntitySet, elementType: PPAModel.PPA_MAT_PARAMETER},
     'PPA_MAT_STRUCTURE_ELEMENT': { type: $data.EntitySet, elementType: PPAModel.PPA_MAT_STRUCTURE_ELEMENT},
     'PPA_MATC_RECORD': { type: $data.EntitySet, elementType: PPAModel.PPA_MATC_RECORD},
     'PPA_MATCR_PARAMETER': { type: $data.EntitySet, elementType: PPAModel.PPA_MATCR_PARAMETER},
     'PPA_MATERIAL': { type: $data.EntitySet, elementType: PPAModel.PPA_MATERIAL},
     'PPA_OEE_SUMMARY': { type: $data.EntitySet, elementType: PPAModel.PPA_OEE_SUMMARY},
     'PPA_PER_DETAIL': { type: $data.EntitySet, elementType: PPAModel.PPA_PER_DETAIL},
     'PPA_PER_RECORD': { type: $data.EntitySet, elementType: PPAModel.PPA_PER_RECORD},
     'PPA_PERIOD': { type: $data.EntitySet, elementType: PPAModel.PPA_PERIOD},
     'PPA_QA_RECORD': { type: $data.EntitySet, elementType: PPAModel.PPA_QA_RECORD},
     'PPA_SHIFT': { type: $data.EntitySet, elementType: PPAModel.PPA_SHIFT},
     'SYS_USER_SESSION': { type: $data.EntitySet, elementType: PPAModel.SYS_USER_SESSION},
     'GetSequenceNextValue': { type: $data.ServiceOperation, returnType: 'Edm.Decimal', method: 'GET', params: [{ name: 'sequenceName', type: 'Edm.String' }] },
     'GetSequenceNextValues': { type: $data.ServiceOperation, returnType: $data.Queryable, elementType: 'Edm.Decimal', method: 'GET', params: [{ name: 'sequenceName', type: 'Edm.String' }, { name: 'count', type: 'Edm.Int32' }] }
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(AicTech.PPA.DataModel.PPAEntities);
  
      
})(window, $data);
      
    